In [57]:
import numpy as np

In [58]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [59]:
def sigmoid_derivative(output):
    return output*(1-output)

In [67]:
x = np.array([[1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
y = np.array([[0,1,1,1]]).T

print "X is : \n",x
print "Y is : \n",y

X is : 
[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
Y is : 
[[0]
 [1]
 [1]
 [1]]


In [68]:
synapse_0 = 2*np.random.random((3,1))-1

In [69]:
print synapse_0.shape
print x.shape

(3, 1)
(4, 3)


In [70]:
for iter in xrange(10000):
    layer_0 = x
    layer_1 = sigmoid(np.dot(layer_0,synapse_0))
    
    layer_1_error = layer_1 - y
    layer_1_delta = layer_1_error*sigmoid_derivative(layer_1)
    synapse_0_derivative = np.dot(layer_0.T,layer_1_delta)
    
    synapse_0 -= synapse_0_derivative

print "Output after training : "
print layer_1
    

Output after training : 
[[ 0.01628029]
 [ 0.98973979]
 [ 0.98973978]
 [ 0.99999822]]


In [71]:
print synapse_0

[[-4.10143798]
 [ 8.67065792]
 [ 8.67065813]]


In [43]:
x.shape

(2, 2)

In [44]:
y.shape

(2, 1)